### PR TITLE
Silence warnings.

### PR DESCRIPTION
**Pull request by dancrossnyc**
Fix a bunch of superfluous warnings from `clang`.

Signed-off-by: Dan Cross <cross@fat-dragon.org>

### CODE REVIEW

**Comment by dancrossnyc** [comment]
Ping?

**Comment by dancrossnyc** [comment]
Just a data point, Fidonet users now confirm that 8364787 fixes ancient-system build problems.

**Comment by dancrossnyc** [comment]
Ping again?

**Comment by shadowlmd** [comment]
@dancrossnyc, I tried to build your fork with latest Visual Studio Community, go this:
```
C:\Git\binkd>nmake /f mkfls\nt95-msvc\Makefile

Microsoft (R) Program Maintenance Utility Version 14.24.28316.0
Copyright (C) Microsoft Corporation.  All rights reserved.

-----------------------------------------------------------
binkd type : msvc
output dir : bin\msvc-binkd
binkd exe  : binkd.exe
-----------------------------------------------------------
Linking binkd.exe...
snprintf.obj : error LNK2005: _vsnprintf already defined in readcfg.obj
snprintf.obj : error LNK2005: _snprintf already defined in readcfg.obj
bin\msvc-binkd\binkd.exe : fatal error LNK1169: one or more multiply defined symbols found
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\bin\HostX86\x86\link.EXE"' : return code '0x491'
Stop.
```
Am I doing something wrong or there is a missing #ifndef somewhere?

**Comment by dancrossnyc** [comment]
My suspicion is a missing #ifdef somewhere, but I didn't touch the vsnprintf/snprintf code paths at all (at least, I don't recall). Does it build at HEAD?

**Comment by shadowlmd** [comment]
I modified Makefile like this:
```$ git diff
diff --git a/mkfls/nt95-msvc/Makefile b/mkfls/nt95-msvc/Makefile
index 37a8cc6..1418969 100644
--- a/mkfls/nt95-msvc/Makefile
+++ b/mkfls/nt95-msvc/Makefile
@@ -49,7 +49,8 @@ CFLAGS=  $(CFLAGS) -nologo -M$(RTLTYPE) -W3 -EHsc -c -J \
          -Fp"$(OBJDIR)\$(BINKDNAME).pch" -Fd"$(OBJDIR)\$(BINKDNAME)"
 CDEFS=   $(CDEFS) -DWIN32 -DHAVE_THREADS -DHAVE_IO_H -DHAVE_DOS_H \
          -DHAVE_STDARG_H -DVISUALCPP -DHTTPS -DAMIGADOS_4D_OUTBOUND -DNTLM \
-         -DHAVE_VSNPRINTF -D_CRT_SECURE_NO_WARNINGS -D_CRT_NONSTDC_NO_DEPRECATE
+         -DHAVE_SNPRINTF -DHAVE_VSNPRINTF -D_CRT_SECURE_NO_WARNINGS \
+         -D_CRT_NONSTDC_NO_DEPRECATE
 OUTDIR=$(OUTDIR)10
 !else
 CFLAGS=  $(CFLAGS) -nologo -M$(RTLTYPE) -W3 -GX -c -YX -J \
```
Compiled successfully with `nmake /f mkfls\nt95-msvc\Makefile MSVC_VER=10 FTS5004=1`.

**Comment by dancrossnyc** [comment]
You'll probably have to parameterize the Makefile so that old versions of MSVC pick up the supplied versions of snprintf et al. However, I think is probably unrelated to the change at hand. I'd send a patch in a separate pull request?

**Comment by pgul** [comment]
Thank you for the pull request and sorry for long delay.

I'm not sure that change `strcmp()` to `streq()` is reasonable.
`strcmp()` is standard, the code is readable and understandable. Anyone who know C language knows its behaviour or can clarify it by `man strcmp`.
Any nonstandard function makes the code less readable. May string be NULL? Does it return 1 or -1 as true?

Any function in tools.c do something more than just call single standard function. If we `#define O_CREATE O_CREAT` for better spelling then code with O_CREATE will looks like typo.

Could you please make pull request with fix warnings separate of the `streq`?

**Comment by dancrossnyc** [comment]
Sure, done.

However, I disagree that `strcmp` is more readable. Yes, it is a standard function, but it is used inconsistently in the `binkd` code: `if (strcmp(...))`, `if (!strcmp())`, `if (strcmp() == 0)` etc are all used, which makes it sometimes difficult to see what the intent is in a given code sequence.

`strcmp` was designed for establishing lexiographic orderings: `streq` is obviously for testing for equality specifically. Moreover, `streq` predates even ANSI C, dating all the way back to C-news: http://www.collyer.net/who/geoff/newspaper.pdf

But as I mentioned in the pull request, I understand that it may be considered controversial, so I don't mind not seeing it introduced.

**Comment by dancrossnyc** [comment]
I guess another ping on this?

**Comment by dancrossnyc** [comment]
Just down to silencing warnings now.

**Comment by pgul** [comment]
Thank you!

**Comment by dancrossnyc** [comment]
Cool; thanks.

**Pull request merged**
